# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-10-03 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validateapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationdata',
            name='email',
            field=models.EmailField(max_length=20),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='firstname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='lastname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='mobile',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='password1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='password2',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
